services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      POSTGRES_DB: crawler
      POSTGRES_USER: crawler
      POSTGRES_PASSWORD: crawler
    ports:
      - '5433:5432'
    volumes:
      - celfit-crawler-pg:/var/lib/postgresql/data

volumes:
  celfit-crawler-pg:
