-- 브랜드 스윕의 통합 풀 파티션 전체 스캔 제거(2026-09-03 monitoring 풀스캔 점검).
--
-- brand_tagged_post의 접근 경로는 PK (brand_id, short_code)와 brand_id 선두 부분 인덱스 2개
-- (direct·hashtag)뿐이라, 스윕이 브랜드마다 도는 taken_at 기반 조회(TaggedPostRepository)는
-- brand_id로 파티션만 좁힌 뒤 그 브랜드가 쌓은 행 전체를 읽고 메모리에서 필터·정렬했다:
--   - trackedPosts / touchCrawledDepth — brand_id = ? AND taken_at >= ? (+ 순수 태그 행 조건)
--   - unenumeratedDuePosts / unenrichedUnenumeratedPosts — taken_at >= ? … ORDER BY taken_at DESC
--   - tagVerifyCandidates — taken_at >= ? … ORDER BY taken_at DESC
--   - touchFrozenHashtag — taken_at >= ? AND taken_at < ? (양쪽 범위가 선택도의 전부)
--   - nthNewestTagTakenAt / nthNewestHashtagTakenAt — ORDER BY taken_at DESC OFFSET n(수천) LIMIT 1
-- 180일 창은 필터일 뿐 삭제가 아니고 해시태그 감시 세트만 브랜드당 2,000이라 파티션은 계속 자란다.
--
-- (brand_id, taken_at) 하나로 위 조회 전부의 범위·정렬을 태운다. 부분 인덱스로 쪼개지 않은 이유:
-- 조회마다 direct/hashtag/tag_detected NULL 조합이 달라(순수 태그·해시태그만·direct∪hashtag)
-- 조합별 부분 인덱스가 3~4개 필요한데, 남는 NULL 플래그 조건은 인덱스가 좁힌 범위 위의 잔여
-- 필터로 충분히 싸다. DESC 정렬은 B-tree 역방향 스캔으로 처리되므로 방향 지정도 두지 않는다.
--
-- 크기: 운영 실측(09-03) 103,693행 기준 bigint+timestamptz 항목 약 32바이트 → 생성 직후 약 3.5 MB,
-- 페이지 분할 후 안정 크기 약 5 MB. taken_at은 브랜드 안에서 대체로 최신순으로 들어와 분할이 적다.
--
-- CONCURRENTLY 미적용 — 선례(V20260827171444)와 같은 판단. brand_tagged_post의 쓰기는 야간 브랜드
-- 스윕(KST 02:00)과 등록 요청뿐이고 마이그레이션은 배포 기동 시점에 돌아 겹치지 않는다. 테이블이
-- 크게 자라면 트랜잭션 밖 별도 마이그레이션으로 CONCURRENTLY 재고할 것.
CREATE INDEX brand_tagged_post_brand_taken_at_idx ON brand_tagged_post (brand_id, taken_at);
